// <auto-generated />
using System;
using ChirpApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChirpApp.Migrations
{
    [DbContext(typeof(ChirpAppContext))]
    [Migration("20250807210256_FixCascadeIssue")]
    partial class FixCascadeIssue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChirpApp.Models.Chirp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(123)
                        .HasColumnType("nvarchar(123)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Chirp");
                });

            modelBuilder.Entity("ChirpApp.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChirpId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChirpId");

                    b.HasIndex("PersonId");

                    b.ToTable("Like");
                });

            modelBuilder.Entity("ChirpApp.Models.Peep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Peep");
                });

            modelBuilder.Entity("ChirpApp.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("ChirpPeep", b =>
                {
                    b.Property<int>("ChirpsId")
                        .HasColumnType("int");

                    b.Property<int>("PeepsId")
                        .HasColumnType("int");

                    b.HasKey("ChirpsId", "PeepsId");

                    b.HasIndex("PeepsId");

                    b.ToTable("ChirpPeep");
                });

            modelBuilder.Entity("ChirpApp.Models.Chirp", b =>
                {
                    b.HasOne("ChirpApp.Models.Person", "Creator")
                        .WithMany("Chirps")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ChirpApp.Models.Like", b =>
                {
                    b.HasOne("ChirpApp.Models.Chirp", "Chirp")
                        .WithMany("Likes")
                        .HasForeignKey("ChirpId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ChirpApp.Models.Person", "Person")
                        .WithMany("Likes")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Chirp");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ChirpPeep", b =>
                {
                    b.HasOne("ChirpApp.Models.Chirp", null)
                        .WithMany()
                        .HasForeignKey("ChirpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChirpApp.Models.Peep", null)
                        .WithMany()
                        .HasForeignKey("PeepsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChirpApp.Models.Chirp", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("ChirpApp.Models.Person", b =>
                {
                    b.Navigation("Chirps");

                    b.Navigation("Likes");
                });
#pragma warning restore 612, 618
        }
    }
}
